name: "Flash CC2531"
version: "1.1.0"
slug: "flashcc2531"
description: "Flash zigbee firmware to CC2531 via GPIO"
url: "https://github.com/powergt/hassio-flashcc2531"
arch:
  - armhf
  - armv7
  - aarch64
startup: once
boot: manual
privileged:
  - SYS_RAWIO
devices:
  - /dev/ttyAMA0:/dev/ttyAMA0:rwm
  - /dev/mem:/dev/mem:rwm
options:
  firmware: "default.hex"
schema:
  firmware: str
