name: "Flash CC2531"
version: "2.0.0"
slug: "flashcc2531"
description: "Flash zigbee firmware to CC2531 via GPIO (Compiled from source)"
url: "https://github.com/powergt/hassio-flashcc2531"
arch:
  - armhf
  - armv7
  - aarch64
startup: once
boot: manual
full_access: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/mem:/dev/mem:rwm
options:
  firmware: "CC2531ZNP-Prod.hex"
schema:
  firmware: str
